# -*- coding: utf-8 -*-
import json, os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

BASE, BOLD = "Helvetica", "Helvetica-Bold"
try:
    f = r"C:\Windows\Fonts"
    pdfmetrics.registerFont(TTFont("A", os.path.join(f, "arial.ttf")))
    pdfmetrics.registerFont(TTFont("AB", os.path.join(f, "arialbd.ttf")))
    BASE, BOLD = "A", "AB"
except Exception as e:
    print("font fallback", e)

DARK = colors.HexColor("#14133a"); GREY = colors.HexColor("#727189")
BG = colors.HexColor("#f4f7ff"); LINE = colors.HexColor("#e2e2eb")
GREEN = colors.HexColor("#1a7a50"); RED = colors.HexColor("#a32d2d")

def money(n):
    return f"{round(n):,} zl".replace(",", " ")

def build(rep, out):
    r = rep["report"]
    story = []
    h1 = ParagraphStyle("h1", fontName=BOLD, fontSize=20, textColor=DARK, leading=24)
    sub = ParagraphStyle("s", fontName=BASE, fontSize=10, textColor=GREY, spaceAfter=14)
    lab = ParagraphStyle("l", fontName=BASE, fontSize=9, textColor=GREY)
    val = ParagraphStyle("v", fontName=BOLD, fontSize=15, textColor=DARK)
    row = ParagraphStyle("r", fontName=BASE, fontSize=11, textColor=DARK)
    story.append(Paragraph("HeyHomie — financial report", h1))
    story.append(Paragraph(f"{rep['title']} &nbsp;·&nbsp; {rep['range']['start']} -> {rep['range']['end']} &nbsp;·&nbsp; VAT {rep['vat']}%", sub))

    kp = [[Paragraph("Revenue (net)", lab), Paragraph("Expenses", lab), Paragraph("Gross margin", lab), Paragraph("Orders", lab)],
          [Paragraph(money(r["revenueNet"]), val), Paragraph(money(r["expenses"]), val), Paragraph(f"{r['grossMarginPct']}%", val), Paragraph(str(r["orders"]), val)]]
    t = Table(kp, colWidths=[42*mm]*4)
    t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),BG),("BOX",(0,0),(-1,-1),6,colors.white),
                           ("INNERGRID",(0,0),(-1,-1),6,colors.white),("TOPPADDING",(0,0),(-1,-1),8),
                           ("BOTTOMPADDING",(0,0),(-1,-1),8),("LEFTPADDING",(0,0),(-1,-1),8)]))
    story.append(t); story.append(Spacer(1,14))

    def line(k, v, bold=False, col=None):
        s = ParagraphStyle("x", fontName=BOLD if bold else BASE, fontSize=11, textColor=col or DARK)
        return [Paragraph(k, row), Paragraph(v, s)]
    bd = [line("Revenue (gross)", money(r["revenueGross"])),
          line("VAT", money(r["vat"])),
          line("Worker payouts", "- "+money(r["workerPayouts"])),
          line("Gross margin", f"{money(r['grossMargin'])}  ·  {r['grossMarginPct']}%", bold=True),
          line("Expenses", "- "+money(r["expenses"])),
          line("Net profit (delta)", f"{money(r['netProfit'])}  ·  {r['netProfitPct']}%", bold=True, col=GREEN if r["netProfit"]>=0 else RED)]
    bt = Table(bd, colWidths=[110*mm, 58*mm])
    bt.setStyle(TableStyle([("LINEBELOW",(0,0),(-1,-2),0.4,LINE),("TOPPADDING",(0,0),(-1,-1),5),
                            ("BOTTOMPADDING",(0,0),(-1,-1),5),("ALIGN",(1,0),(1,-1),"RIGHT")]))
    story.append(bt); story.append(Spacer(1,18))

    story.append(Paragraph("Monthly breakdown", ParagraphStyle("mb", fontName=BOLD, fontSize=13, textColor=DARK, spaceAfter=6)))
    data = [[Paragraph(x, ParagraphStyle("th", fontName=BOLD, fontSize=9, textColor=colors.white)) for x in ["Month","Orders","Revenue (net)","Gross margin"]]]
    for m in rep["monthly"]:
        data.append([Paragraph(m["month"], row), Paragraph(str(m["orders"]), row), Paragraph(money(m["revenueNet"]), row), Paragraph(money(m["grossMargin"]), row)])
    dt = Table(data, colWidths=[50*mm, 30*mm, 44*mm, 44*mm])
    dt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),DARK),("LINEBELOW",(0,0),(-1,-1),0.4,LINE),
                            ("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6),
                            ("ALIGN",(1,0),(-1,-1),"RIGHT")]))
    story.append(dt); story.append(Spacer(1,18))
    story.append(HRFlowable(width="100%", thickness=0.5, color=LINE)); story.append(Spacer(1,6))
    story.append(Paragraph("Generated by HeyHomie admin. Figures are indicative until reconciled with accounting.",
                           ParagraphStyle("f", fontName=BASE, fontSize=8, textColor=GREY)))
    SimpleDocTemplate(out, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm, topMargin=18*mm, bottomMargin=16*mm).build(story)
    print("written", out)

d = json.load(open("reports.tmp.json", encoding="utf-8"))
build(d["q2"], r"C:\Users\ihorf\Downloads\HeyHomie_Report_Q2_2025.pdf")
build(d["year"], r"C:\Users\ihorf\Downloads\HeyHomie_Report_Year_2025.pdf")
