/**
 * HeyHomie — orders, recurring services and missions.
 *
 * Key distinction (used everywhere in the UI):
 *  - Order   = a one-off booking that produces a single Mission.
 *  - Service = a recurring subscription that GENERATES Missions on a schedule.
 *  - Mission = one cleaning job: time-based (min 3h) + a travel buffer, with a
 *              status lifecycle owned by the worker/admin and mirrored to the client.
 */

import type { CleaningPlan, CleaningParams, SelectedAddOn } from './cleaning';

/** Mission status — mirrors the Go API. */
export type MissionStatus =
    | 'searching_homie'
    | 'homie_found'
    | 'in_progress'
    | 'done'
    | 'canceled'
    | 'unpaid'
    | 'freezed';

/**
 * Once a homie is found the mission snapshot is shared with the Go side, so its
 * attributes must not be edited afterwards (only `searching_homie` is editable).
 * See the Rails<->Go sync rules.
 */
export const FROZEN_STATUSES: MissionStatus[] = ['homie_found', 'in_progress', 'done', 'canceled', 'unpaid', 'freezed'];

export const isMissionEditable = (status: MissionStatus): boolean => status === 'searching_homie';

export type PaymentMethod = 'pay_later' | 'cash' | 'card';

export type Frequency = 'once' | 'weekly' | 'biweekly' | 'monthly';

export interface Address {
    id: string;
    name: string; // "Home", "Work"
    line1: string;
    zipCode: string;
    city: string;
    notes?: string; // entry code, floor, etc.
}

export interface PersonRef {
    id: string;
    firstName: string;
    lastInitial?: string; // privacy: clients see only first name + initial
    avatarUrl?: string;
    rating?: number;
}

export interface Mission {
    id: string;
    status: MissionStatus;
    plan: CleaningPlan;
    /** The three main calculator variables (rooms / kitchens / bathrooms). */
    params: CleaningParams;
    addOns: SelectedAddOn[];
    /** Just informational — are there pets at the address? Price is unchanged. */
    petsPresent?: boolean;
    /** When the order was created / started searching (ISO). */
    createdAt?: string;
    /** When a homie was found (ISO) — used for time-to-assignment. */
    assignedAt?: string;
    /** Scheduled start (ISO). */
    scheduledAt: string;
    /** Estimated work time, minutes (>= 180). Travel buffer is separate. */
    durationMinutes: number;
    travelBufferMinutes: number;
    /** Homies assigned to this mission (general can be a 2-person team). */
    workerCount: 1 | 2;
    address: Address;
    client: PersonRef;
    homie?: PersonRef; // absent while searching_homie
    homieEtaAt?: string; // when "on the way"
    /** Worker check-in / check-out timestamps (ISO), set on the ground. */
    checkInAt?: string;
    checkOutAt?: string;
    price: number;
    currency: string; // 'PLN'
    /** Set when this mission was generated by a recurring service. */
    serviceId?: string;
    rating?: number;
    photos?: string[]; // client report photos (if something was wrong)
}

export interface Order {
    id: string;
    kind: 'order';
    mission: Mission;
    paymentMethod: PaymentMethod;
    createdAt: string;
}

export interface RecurringService {
    id: string;
    kind: 'service';
    plan: CleaningPlan;
    addOns: SelectedAddOn[];
    frequency: Exclude<Frequency, 'once'>;
    /** The permanently assigned homie for this service. */
    assignedHomie?: PersonRef;
    address: Address;
    paymentMethod: PaymentMethod;
    active: boolean;
    /** Upcoming generated missions. */
    upcomingMissions: Mission[];
}

export const isFrozen = (m: Mission): boolean => FROZEN_STATUSES.includes(m.status);

/** Total client-facing time window for a mission: work + travel buffer. */
export const totalBlockedMinutes = (m: Pick<Mission, 'durationMinutes' | 'travelBufferMinutes'>): number =>
    m.durationMinutes + m.travelBufferMinutes;
